apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spark-monitor
  namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      spark-role: driver
  podMetricsEndpoints:
  - port: spark-ui
    path: /metrics/prometheus
    interval: 15s
  - port: spark-ui
    path: /metrics/executors/prometheus
    interval: 15s
