spec:
  template:
    spec:
      containers:
        - name: server
          volumeMounts:
            - name: custom-server-config
              mountPath: /home/unitycatalog/etc/conf/server.properties
              subPath: server.properties
      volumes:
        - name: custom-server-config
          configMap:
            name: unity-catalog-server-config
