spec:
  template:
    spec:
      containers:
        - name: server
          command: ["bin/start-uc-server"]
          args: ["-p", "8085"]
          ports:
            - containerPort: 8085
              name: api-8085
          startupProbe:
            tcpSocket:
              port: 8085
          volumeMounts:
            - name: custom-server-config
              mountPath: /home/unitycatalog/etc/conf/server.properties
              subPath: server.properties
      volumes:
        - name: custom-server-config
          configMap:
            name: unity-catalog-server-config
