apiVersion: v1
kind: Service
metadata:
  name: spark-driver-headless
  namespace: default
  labels:
    app: spark-driver-headless
spec:
  clusterIP: None
  selector:
    spark-role: driver
  ports:
  - name: spark-ui
    port: 4040
    targetPort: 4040
