apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: centralized-ingress
  namespace: default
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  # Airflow
  - host: airflow.INGRESS_DOMAIN
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: airflow-webserver
            port:
              number: 8080
  # MinIO Console
  - host: minio.INGRESS_DOMAIN
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 9001
  # MinIO API
  - host: s3.INGRESS_DOMAIN
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 9000
  # Superset
  - host: superset.INGRESS_DOMAIN
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: superset
            port:
              number: 8088
  # Zeppelin
  - host: zeppelin.INGRESS_DOMAIN
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zeppelin
            port:
              number: 8080
  # Spark UI
  - host: spark.INGRESS_DOMAIN
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zeppelin
            port:
              number: 4040

