apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spark-service-monitor
  namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: zeppelin
  endpoints:
  - port: spark-ui
    path: /metrics/prometheus
    interval: 15s
  - port: spark-ui
    path: /metrics/executors/prometheus
    interval: 15s
