apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spark-driver-monitor
  namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: spark-driver-headless
  endpoints:
  - port: spark-ui
    path: /metrics/prometheus
    interval: 10s
